language: java
jdk:
  - openjdk8
  - oraclejdk8
dist: trusty

before_install:
  - sudo add-apt-repository ppa:mmk2410/intellij-idea -y
  - sudo apt-get update -q
  - sudo apt-get install intellij-idea-community -y
  - sudo apt-get install groovy -y

install:
  - ./gradlew assemble
  - sudo chmod -R aog+w /opt/intellij-idea-community/bin

script:
 - ./gradlew check
 # Copy idea configuration template (mostly .IntelliJIdea2018.1/config/options/jdk.table.xml)
 - cp -r ./dev/idea-cli-inspector/root/.IntelliJIdea2018.1 /home/travis/
 #- ./idea-cli-inspector-master/ideainspect.groovy -i  /opt/intellij-idea-community
 - ./dev/idea-cli-inspector/ideainspect.groovy -i /opt/intellij-idea-community
