language: java

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

jobs:
 include:
    - stage: test
      name: Run default tests and code quality checks
      jdk: openjdk8
      script: ./gradlew check -x detekt
    - jdk: openjdk8
      env: validate
      script: ./gradlew detekt
    - stage: test
      dist: trusty
      name: Test on OracleJdk
      jdk: oraclejdk8
      script: ./gradlew check -x detekt

